### ISSUE TITLE
undefined method `accept_encoding' for #<Rack::Request:0x3e0d14>

### ISSUE THREAD

**Issue by ismell** [jruby/jruby-rack#86]
I'm getting the following exception when I upgraded from 1.0.9 to 1.1.3:

> 2012-01-17 11:53:57.266:WARN:/:Application Error
> org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `accept_encoding' for #Rack::Request:0x3e0d14
>         at Rack::Deflater.call(file:/home/me/.m2/repository/org/jruby/rack/jruby-rack/1.1.3/jruby-rack-1.1.3.jar!/vendor/rack-1.3.6/rack/deflater.rb:25)
>         at Rack::Handler::Servlet.call(file:/home/me/.m2/repository/org/jruby/rack/jruby-rack/1.1.3/jruby-rack-1.1.3.jar!/rack/handler/servlet.rb:20)

Acoring to kares:

> < kares> ismell: seems like Rack::Request did not load correctly from rack's "rack/request.rb" but only from "jruby/rack/rack_ext.rb"
> < kares> ismell: seems there should be a require in rack_ext - could you fill an issue with the env you reproduced it ?

config.ru

``` ruby
require 'rubygems'
require 'LoggerFactory'
LoggerFactory.print_state

require 'PageBuilder'

use Rack::Deflater

app  = PageBuilder.new

run app 
```

PageBuilder.rb

``` ruby
require 'java'
require 'json'
require 'net/http'
require 'uri'
require 'cgi'
require 'mongo'
require 'DeepMerge'
require 'ProducerDatabase'
require 'SoftwareDatabase'
require 'ConfigurationDataStore'
require 'PackageDataStore'
require 'ManifestDataStore'
require 'PageDataStore'
require 'SitemapDataStore'
require 'TofuDataStore'
require 'LoggerFactory'
require 'json'

class PageBuilder

  @@log = LoggerFactory.getLogger("com.test.pagebuilder.PageBuilder")
  def initialize()

  end

  def call(env)
     ...
  end
end
```
